version: 2.1

jobs:
  # Job one with a unique name
  say_hi_to_yml:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hi to YAML!"

workflows:
  # Name of workflow
  hi_1:
    # List of jobs that will run
    jobs:
      - say_hi_to_yml
  hi_2:
    jobs:
      - say_hi_to_yml
  hi_3:
    jobs:
      - say_hi_to_yml
  hi_4:
    jobs:
      - say_hi_to_yml
  hi_5:
    jobs:
      - say_hi_to_yml
  hi_6:
    jobs:
      - say_hi_to_yml
  hi_7:
    jobs:
      - say_hi_to_yml
